<a href="https://colab.research.google.com/github/KiarashVaziri/Introduction-to-Machine-Learning/blob/main/CHW398102562.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Intro to Machine Learning <br />
##Computer Homework 3 <br />
*Name: Kiarash Vaziri* <br />
*Student Number: 98102562* <br />


# C5: Multiclass Classification

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import keras
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.losses import categorical_crossentropy
import matplotlib.pyplot as plt

In [ ]:
# data loading
from google.colab import drive 
drive.mount('/media/gdrive', force_remount=True)
dataSet = pd.read_csv(r"/media/gdrive/MyDrive/MachineLearning/CHW3/fashion-mnist.csv")


Mounted at /media/gdrive


In [ ]:
trainPercentage = 0.50
validPercentage = 0.35
testPercentage = 0.15

x = dataSet.loc[:, '0':'783']
y = dataSet.loc[:, 'y']

xt = x.loc[0:int(trainPercentage*len(x)), :]
yt = y.loc[0:int(trainPercentage*len(y))]

xv = x.loc[int(trainPercentage*len(x))+1:int(trainPercentage*len(x))+int(validPercentage*len(x)), :]
yv = y.loc[int(trainPercentage*len(y))+1:int(trainPercentage*len(y))+int(validPercentage*len(y))]

xtest = x.loc[int(trainPercentage*len(x))+int(validPercentage*len(x))+1:len(x), :]
ytest = y.loc[int(trainPercentage*len(y))+int(validPercentage*len(y))+1:len(y)]

## Confusion Matrix
Furthremore, we will use the following function from sklearn library to calculate confusion matrix:

```
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_true, y_pred)
```


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

## 1. SVM with Linear Kernel 
The objective of a Linear SVC (Support Vector Classifier) is to fit to the data you provide, returning a "best fit" hyperplane that divides, or categorizes, your data.


```
from sklearn import svm
clf = svm.SVC(kernel='linear')
clf_trained_model = clf.fit(X,y)
```

Also by using the following function, we can predict and validate:

```
clf_trained_model.predict(xvalidation)
```



In [ ]:
from sklearn.svm import SVC

# 1st method: SVM with Linear Kernel
clf = SVC(kernel = 'linear')
clf_trained_model = clf.fit(xt, yt)
y_predicted = clf_trained_model.predict(xv)
confusion_matrix_SVM = confusion_matrix(yv, y_predicted)

print(f"SVM with linear kernel results the following confusion matrix:\n{confusion_matrix_SVM}")

accuracy_SVM = accuracy_score(yv, y_predicted)
print(f"Accuracy score of SVM with linear kernel is {accuracy_SVM}")

SVM with gaussian kernel results the following confusion matrix:
[[253   4   6  11   1   0  46   0   5   0]
 [  4 338   1   5   0   0   0   0   0   0]
 [ 12   2 250   3  37   0  42   0   3   0]
 [ 30   9   5 276   8   0   5   0   1   0]
 [  4   2  61  22 233   0  36   0   2   0]
 [  0   0   0   0   1 276   0  16   2   2]
 [ 64   1  45  11  37   0 199   0   3   0]
 [  0   0   0   0   0  21   0 364   1  15]
 [  5   0   3   1   1   2  12   3 341   2]
 [  0   0   0   0   0  14   0  21   0 320]]
Accuracy score of SVM with linear kernel is 0.8142857142857143


## 2. SVM with Gaussian Kernel
Most of the modeling is the same as the previous method with the diffrence that here we have to find an optional parameter, 𝞂, that has to be set optimally.

In [ ]:
from sklearn.svm import SVC

# 2nd method: SVM with Gaussian Kernel
sigmas = np.logspace(-10, 0, num = 11)
accuracy_SVM = []

for i in range(len(sigmas)):
  clf = SVC(kernel = 'rbf', gamma = sigmas[i])
  clf_trained_model = clf.fit(xt, yt)
  y_predicted = clf_trained_model.predict(xv)
  accuracy_SVM.append(accuracy_score(yv, y_predicted))

max_accuracy = max(accuracy_SVM)
max_index = accuracy_SVM.index(max_accuracy)

clf = SVC(kernel = 'rbf', gamma = sigmas[max_index])
clf_trained_model = clf.fit(xt, yt)
y_predicted = clf_trained_model.predict(xv)

confusion_matrix_SVM = confusion_matrix(yv, y_predicted)
print(f"SVM with gaussian kernel results the following confusion matrix:\n{confusion_matrix_SVM}")
print(f"Accuracy score of SVM with gaussian kernel is {max_accuracy}")

SVM with gaussian kernel results the following confusion matrix:
[[277   2   3  16   0   0  21   0   7   0]
 [  2 327   2  16   0   0   1   0   0   0]
 [  7   0 265   7  40   0  28   0   2   0]
 [ 16   0   0 302   9   0   7   0   0   0]
 [  2   1  31  18 267   0  39   0   2   0]
 [  0   0   0   0   0 269   0  22   2   4]
 [ 88   1  42   8  34   0 182   0   5   0]
 [  0   0   0   0   0  17   0 365   0  19]
 [  2   0   2   3   1   2   8   3 347   2]
 [  0   0   0   0   0   6   0  17   0 332]]
Accuracy score of SVM with linear kernel is 0.838


We can see with signa = 10^-7 we find the best result.

## 3. K-nearest Neighbors 
In order to implement this method, we use the following function from scikit-learn library:

```
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = k)
clf.fit(X_train, y_train)
```

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

training = []
scores = []
  
for k in range(2, 10):
    clf = KNeighborsClassifier(n_neighbors = k)
    clf.fit(xt, yt)
    training_score = clf.score(xv, yv)
    training.append(training_score)
    scores.append(training_score)

max_accuracy = max(scores)
print(f"max_index or k is {max_index}")
max_index = scores.index(max_accuracy)

clf = KNeighborsClassifier(n_neighbors = k)
clf_trained_model = clf.fit(xt, yt)
y_predicted = clf_trained_model.predict(xv)
model_accuracy = accuracy_score(yv, y_predicted)

confusion_matrix_SVM = confusion_matrix(yv, y_predicted)
print(f"K-nearest neighbors results the following confusion matrix:\n{confusion_matrix_SVM}")
print(f"Accuracy score of K-nearest neighbors is {model_accuracy}")

max_index or k is 0
K-nearest neighbors results the following confusion matrix:
[[277   2   8   9   1   0  25   0   4   0]
 [  4 329   3   9   0   0   3   0   0   0]
 [  9   0 243   4  45   0  47   0   1   0]
 [ 20   3   0 290  12   0   8   0   1   0]
 [  0   1  52  25 236   0  45   0   1   0]
 [  3   0   2   0   0 218   0  50   2  22]
 [ 92   1  49   8  33   1 174   0   2   0]
 [  0   0   0   0   0   4   0 369   0  28]
 [  1   0   9   5   5   0  12  10 324   4]
 [  0   0   0   0   0   1   0  13   0 341]]
Accuracy score of K-nearest neighbors is 0.8002857142857143


As found above, we can conclude that for k=2 the accuracy is maximum.

## 4. Decision Tree
For this section we use the already-built-it model of scikit-learn library.


```
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf_trained_model = clf.fit(xt, yt)
```



In [ ]:
from sklearn.tree import DecisionTreeClassifier

# 4. Decision tree 

clf = DecisionTreeClassifier()
clf_trained_model = clf.fit(xt, yt)
y_predicted = clf_trained_model.predict(xv)
model_accuracy = accuracy_score(yv, y_predicted)

confusion_matrix_SVM = confusion_matrix(yv, y_predicted)
print(f"Decision tree method results the following confusion matrix:\n{confusion_matrix_SVM}")
print(f"Accuracy score of Decision tree is {model_accuracy}")

Decision tree method results the following confusion matrix:
[[230   4   7  24   4   4  43   0   9   1]
 [  2 319   0  19   2   0   2   0   4   0]
 [ 13   0 218   7  55   1  48   0   7   0]
 [ 14  13   4 258  26   2  13   0   4   0]
 [  6   7  72  18 204   0  46   0   7   0]
 [  1   1   3   1   0 241   1  28   6  15]
 [ 55   5  56  17  46   3 169   0   9   0]
 [  0   0   0   0   0  31   0 308   2  60]
 [  3   2  17   6   9   8  15   5 300   5]
 [  1   0   1   1   0  17   0  32   2 301]]
Accuracy score of Decision tree is 0.728


## 5. Neural Networks
For creating a neural network we should take a few steps, first we build the model of out neural network.

In [ ]:
# 5. Neural Networks
# building the model

model = keras.Sequential([
    keras.layers.Input(shape=(784,)),                                   # input layer (1)
    keras.layers.Dense(100, activation='relu'),                         # hidden layer (2)
    keras.layers.Dense(100, activation='relu'),                         # hidden layer (3)
    keras.layers.Dense(10, activation='softmax')                        # output layer (4)
])

Before the model is ready for training, it needs a few more settings. These are added during the model's compile step:
* loss function
*  optimizer
*  metrics


In [ ]:
# compile the model
model.compile(
    loss='categorical_crossentropy', 
    optimizer='sgd', 
    metrics=['accuracy']
)

Since our train label list is one-dimensional, we convert it into a categorical list.

In [ ]:
yt_categorical = np_utils.to_categorical(yt)
yv_categorical = np_utils.to_categorical(yv)

Now, we are prepared to train our model. To start training, call the model.fit method—so called because it "fits" the model to the training data:

In [ ]:
trained_nn = model.fit(xt, yt_categorical, epochs = 400, verbose = 0)

In [ ]:
empirical_error = model.evaluate(xt, yt_categorical, verbose=0)
true_risk = model.evaluate(xv, yv_categorical, verbose=0)
print(empirical_error)
print(true_risk)

[2.3019254207611084, 0.10677864402532578]
[2.3037219047546387, 0.09542857110500336]


In [ ]:
ynn_predicted = model.predict(xv)
cm = confusion_matrix(yv, ynn_predicted)

[0.10208514 0.10154129 0.10342988 0.10667942 0.09354644 0.09602649
 0.10033685 0.09676646 0.10100774 0.09858031]


# Conclusion
As calculated above, we pick SVM with **gaussian kernel function**.

In [ ]:
from sklearn.svm import SVC

# 2nd method: SVM with Gaussian Kernel
# testing the test data 
sigma = 1e-7
clf = SVC(kernel = 'rbf', gamma = sigma)
clf_trained_model = clf.fit(xt, yt)
ytest_predicted = clf_trained_model.predict(xtest)
test_accuracy = accuracy_score(ytest, ytest_predicted)

confusion_matrix_SVM = confusion_matrix(ytest, ytest_predicted)
print(f"SVM with gaussian kernel results the following test confusion matrix:\n{confusion_matrix_SVM}")
print(f"Test accuracy score of SVM with gaussian kernel is {test_accuracy}")

SVM with gaussian kernel results the following test confusion matrix:
[[129   0   0  11   0   0   7   0   1   0]
 [  2 127   4   9   0   0   0   0   2   0]
 [  1   0 118   3  27   0  14   0   0   0]
 [  8   2   0 132   3   0   3   0   0   0]
 [  2   0   8   7 122   0  20   0   0   0]
 [  0   0   0   0   0 125   0  11   1   3]
 [ 39   0  16   5  11   0  79   0   1   0]
 [  0   0   0   0   0   4   0 147   0   3]
 [  1   0   3   0   0   2   4   1 129   0]
 [  0   0   0   0   0   4   0   7   0 141]]
Test accuracy score of SVM with gaussian kernel is 0.8332221480987325
